name: Deploy Master to Amazon ECS

on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/workflow.yml
    with:
      router_image: 'ghcr.io/geode-solutions/opengeodeweb-router:master'
      router_logs: '/ecs/Website-Master/router/'
      viewer_image: 'ghcr.io/geode-solutions/opengeodeweb-viewer:master'
      viewer_logs: '/ecs/Website-Master/viewer/'
      geode_image: 'ghcr.io/geode-solutions/website-back:master'
      geode_logs: '/ecs/Website-Master/geode/'
      task: 'Website-Master'
      cluster: 'Website-Master'
      memory: '2048'
      cpu: '1024'
    secrets: inherit
